SELECT NAME || '(' || SUBSTR(OCCUPATION, 0, 1) || ')' FROM OCCUPATIONS 
       ORDER BY NAME;

SELECT 'There are a total of ' || COUNT(*) || ' ' || LOWER(OCCUPATION) || 's.' FROM OCCUPATIONS 
        GROUP BY OCCUPATION 
        ORDER BY COUNT(*), OCCUPATION;
